/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0.2/userguide/building_java_projects.html
 */

plugins {
   id("org.openjfx.javafxplugin") version "0.0.10"
   application
}

repositories {
   mavenCentral()
}

javafx {
   version = "16"
   modules("javafx.base","javafx.controls", "javafx.fxml")
   configuration = "implementation"
}

dependencies {
   implementation("com.google.guava:guava:30.1-jre")
   implementation("net.sf.biweekly:biweekly:0.6.6")
   implementation("com.google.code.gson:gson:2.8.7")

   compileOnly("org.projectlombok:lombok:1.18.20")
   annotationProcessor("org.projectlombok:lombok:1.18.20")

   testImplementation("org.junit.jupiter:junit-jupiter:5.7.1")
   testCompileOnly("org.projectlombok:lombok:1.18.20")
}

application {
   mainClass.set("ucf.assignments.App")
}

tasks.test {
   useJUnitPlatform()
}